account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from django.conf.urls.static import static


app_name = 'account'
urlpatterns = [
    path(
        'login/', 
        auth_views.LoginView.as_view(template_name='account/login_form.html'), 
        name='login'
    ),
    path('signup/', views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard-friendships/', views.dashboard_friendship, name='friendship'),
    path(
        'dashboard-sent-requests/',
        views.dashboard_sent_friendship_requests, 
        name='sent-requests'
    ),
    path(
        'dashboard-received-requests/',
        views.dashboard_received_friendship_requests, 
        name='received-requests'
    ),
    path(
        'user/<int:pk>/', 
        views.UserDetailView.as_view(), 
        name='detail'
    ),
]

budget/urls.py
from django.urls import path
from . import views

app_name = 'budget'
urlpatterns = [
    path('', views.BudgetCreateView.as_view(), name='create'),
    path('list/', views.BudgetListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.BudgetDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.BudgetUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.BudgetDeleteView.as_view(), name='delete'),
]

custom_account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from django.conf.urls.static import static


app_name = 'custom_account'
urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard-friendships/', views.dashboard_friendship, name='friendship'),
    path(
        'dashboard-sent-requests/',
        views.dashboard_sent_friendship_requests, 
        name='sent-requests'
    ),
    path(
        'dashboard-received-requests/',
        views.dashboard_received_friendship_requests, 
        name='received-requests'
    ),
    path(
        'dashboard-budgets/',
        views.dashboard_budgets,
        name='budgets'
    ),
    path(
        'user/<int:pk>/', 
        views.UserDetailView.as_view(), 
        name='detail'
    ),
]

errand/urls.py
from django.contrib import admin
from django.urls import path, include
from custom_account.views import home as home_view
from django.conf.urls.static import static
from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('custom-accounts/', include('custom_account.urls')),
    path('item/', include('item.urls')),
    path('sharing/', include('sharing.urls')),
    path('friendship/', include('friendship.urls')),
    path('budget/', include('budget.urls')),
    path('', home_view)
]

if DEBUG:
     urlpatterns+=static(MEDIA_URL, document_root=MEDIA_ROOT)

friendship/urls.py
from django.urls import path
from . import views

app_name = 'friendship'

urlpatterns = [
    path(
        'unfriend/<int:pk>/', 
        views.UnfriendView.as_view(), 
        name='unfriend'
    ),
    path(
        'block/<int:pk>/',
        views.BlockUnblockUserView.as_view(),
        name='block'
    ),
    path(
        'search/',
        views.friend_search,
        name='search'
    ),
    path(
        'request/<int:pk>/<int:friend_id>/',
        views.CreateFriendshipRequest.as_view(),
        name='request'
    ),
    path(
        'accept/<int:friend_id>/',
        views.AcceptFriendshipRequest.as_view(),
        name='accept'
    )
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'
urlpatterns = [
    path('item/<int:budget_id>/', views.ItemCreateView.as_view(), name='create'),
    path('list/', views.ItemListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.ItemDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', views.ItemDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', views.ItemUpdateView.as_view(), name='update'),
]

custom_account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.conf import settings
from django.utils.translation import gettext_lazy as _


class CustomUserManager(UserManager):

    def _create_user(self, email, password, username, **extra_fields):
        if not email:
            raise ValueError("Email must be set")

        if not username:
            raise ValueError("Username must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, username **extra_fields)
    
    def create_superuser(self, email, username, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self._create_user(email, password, username, **extra_fields)


class User(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(_('username'), max_length=50, unique=True)
    objects = CustomUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email


class Profile(models.Model):
    """
    Model to represent user's profile. 
    """
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='profile'
    )
    bio = models.TextField()
    photo = models.ImageField(upload_to=f'media/profiles/')

    def __str__(self):
        return f"{self.__class__.__name__} object for {self.user}"

custom_account/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from reviews.models import Review
from item.models import Item
from friendship.models import Friendship
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from . import utils
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required


@login_required
def profile(request):
    return render(request, 'custom_account/profile.html')


def home(request):
    reviews = Review.objects.all()[:3]
    return render(request, "home.html", {"reviews": reviews})

@login_required
def dashboard(request):
    return render(request, "custom_account/dashboard_item.html", 
        utils.get_dashboard_contents(request)
    )

@login_required
def dashboard_friendship(request):
    return render(request, "custom_account/dashboard_friendship.html", 
        utils.get_dashboard_contents(request)
    )

@login_required
def dashboard_sent_friendship_requests(request):
    return render(request, "custom_account/dashboard_sent_requests.html", 
        utils.get_dashboard_contents(request)
    )

@login_required
def dashboard_received_friendship_requests(request):
    return render(
        request,
        "custom_account/dashboard_received_requests.html", 
        utils.get_dashboard_contents(request)
    )

@login_required
def dashboard_budgets(request):
    return render(
        request, 
        "custom_account/dashboard_budget.html",
        utils.get_dashboard_contents(request)
    )

class UserList(generic.ListView):
    model = get_user_model()


class UserDetailView(LoginRequiredMixin, generic.DetailView):
    model = get_user_model()
    template_name = 'custom_account/user_detail.html'

custom_account/templates/custom_account/dashboard_base.html
{% extends "base.html" %}
{% load  account_extras %}
{% block content %}
    <section class="dashboard-container">
        <aside class="aside-dashboard">
            <h4 class="tab-title" style="display: inline-block; color: white;">
                <!-- check if the path matches a given path -->
                {% if request.path|get_route == "dashboard-received-requests" %}
                    Received requests({{received_friendship_requests|length}}): 
                {% elif request.path|get_route == "dashboard-sent-requests" %}
                    Sent requests({{sent_friendship_requests|length}}): 
                {% elif request.path|get_route == "dashboard-budgets" %}
                    Budgets({{budgets|length}}): 
                    <a 
                        style="color: white;" 
                        class="nav-link secondary-color btn-bordered-secondary" 
                        href="{% url 'budget:create' %}"
                    > 
                        &plus; Create
                    </a>
                {% elif request.path|get_route == "dashboard-friendships" %}
                    Friends ({{friendships|length}}): 
                {% endif %}
            </h4>
            
            <!-- {% include 'brand.html' %}
            <ul class="item-aside">
                {% block budget_link %}
                    <li class="nav-item hover-border">
                        <i class="fa-solid fa-list fa-lg"></i>
                        <a class="nav-link" href="{% url 'custom_account:budgets' %}">Budgets 
                            <span class="badge primary-bg secondary">{{budgets|length}}</span>
                        </a>
                        <a class="nav-link primary-color" href="{% url 'budget:create' %}"> 
                            &plus; New
                        </a>
                    </li>
                {% endblock %}
             
                {% block friendship_link %}
                    <li class="nav-item hover-border">
                        <i class="fa-solid fa-user-group"></i>
                        <a class="nav-link" href="{% url 'custom_account:friendship' %}">Friends
                            <span class="badge primary-bg secondary">{{friendships|length}}</span>
                        </a>
                    </li>
                {% endblock %}
                {% block received_requests_link %}
                    <li class="nav-item hover-border">
                        <i class="fa-solid fa-circle-down"></i>
                        <a class="nav-link" href="{% url 'custom_account:received-requests' %}">Requests
                            <span class="badge primary-bg secondary">{{received_friendship_requests|length}}</span>
                        </a>
                    </li>
                {% endblock %}
                {% block sent_requests_link %}
                    <li class="nav-item hover-border">
                        <i class="fa-solid fa-paper-plane"></i>
                        <a class="nav-link" href="{% url 'custom_account:sent-requests' %}">Requests
                            <span class="badge primary-bg secondary">{{sent_friendship_requests|length}}</span>
                        </a>
                    </li>
                {% endblock %}
            </ul> -->
        </aside>
        <div>
            <!-- <header class="dashboard primary-bg">
                <i class="fas fa-bars"></i>
                <small style="color: orange;">
                    {% if friendships %}
                        {{friendships|length}}
                    {% elif sent_friendship_requests %}
                        You have sent {{sent_friendship_requests|length}} friend request{{sent_friendship_requests|pluralize}}
                    {% elif received_friendship_requests %}
                        You have received {{received_friendship_requests|length}} friend request{{received_friendship_requests|pluralize}}
                    {% elif budgets %}
                        You {{budgets|length}} budget{{budgets|pluralize}}
                    {% endif %}
                </small>
            </header> -->
            <main class="items-main reviews-container padding-main-bottom padding-main-x overflow-y">
                {% block dashboard_content %}{% endblock %}
            </main>
        </div>
    </section>
{% endblock %}

custom_account/templates/custom_account/dashboard_budget.html
{% extends "custom_account/dashboard_base.html" %}

<!-- Make item link active -->
{% block budget_link %}
<li class="nav-item hover-border active">
    <i class="fa-solid fa-list fa-lg"></i>
    <a class="nav-link" href="{% url 'custom_account:dashboard' %}">Items 
        <span class="badge primary-bg secondary">{{budgets|length}}</span>
    </a>
    <a class="nav-link primary-color" href="{% url 'budget:create' %}"> &plus; New
    </a>
</li>
{% endblock %}
{% block dashboard_content %}
    {% for budget in  budgets %}
        {% include "budget/budget.html" %}
    {% empty %}
        <div style="text-align: center; margin: auto;">
            <p>You don't have budgets yet. </p>
            <a class="btn-bordered-primary nav-link" href="{% url 'budget:create' %}"> &plus; Create</a>
        </div>
    {% endfor %}
{% endblock %}

custom_account/templates/custom_account/dashboard_friendship.html
{% extends "custom_account/dashboard_base.html" %}

<!-- make friendship link active -->
{% block friendship_link %}
    <li class="nav-item active">
        <i class="fa-solid fa-user-group"></i>
        <a class="nav-link" href="{% url 'custom_account:friendship' %}">Friends
            <span class="badge primary-bg secondary">{{friendships|length}}</span>
        </a>
    </li>
{% endblock %}

{% block dashboard_content %}
    {% for friendship in  friendships %}
        {% include "friendship/friend.html" with friend=friendship %}
    {% empty %}
        <div style="text-align: center; margin: auto; ">
            <h4>You don't have friends yet.</h4>
            <p>Search for friends and send them friendship requests</p>
        </div>
    {% endfor %}
{% endblock %}

custom_account/templates/custom_account/dashboard_item.html
{% extends "custom_account/dashboard_base.html" %}

<!-- Make item link active -->
{% block items_link %}
<li class="nav-item hover-border active">
    <i class="fa-solid fa-list fa-lg"></i>
    <a class="nav-link" href="{% url 'custom_account:dashboard' %}">Items 
        <span class="badge primary-bg secondary">{{items|length}}</span>
    </a>
    <a class="nav-link primary-color" href="{% url 'item:create' %}"> &plus; Add
    </a>
</li>
{% endblock %}
{% block dashboard_content %}
    {% for item in  items %}
        {% include "item/item.html" %}
    {% endfor %}
{% endblock %}

custom_account/templates/custom_account/dashboard_received_requests.html
{% extends "custom_account/dashboard_base.html" %}
<!-- make friendship link active -->
{% block received_requests_link %}
<li class="nav-item hover-border active">
    <i class="fa-solid fa-circle-down"></i>
    <a class="nav-link" href="{% url 'custom_account:received-requests' %}">Requests
        <span class="badge primary-bg secondary">{{received_friendship_requests|length}}</span>
    </a>
</li>
{% endblock %}

{% block dashboard_content %}
    {% for friendship_request in received_friendship_requests %}
       {% include "friendship/received_request.html" %}
    {% empty %}
       <p>You have not received any friend request.</p>
    {% endfor %}
{% endblock %}

custom_account/templates/custom_account/dashboard_sent_requests.html
{% extends "custom_account/dashboard_base.html" %}

<!-- make friendship link active -->
{% block sent_requests_link %}
<li class="nav-item hover-border active">
    <i class="fa-solid fa-paper-plane"></i>
    <a class="nav-link" href="{% url 'custom_account:sent-requests' %}">Requests
        <span class="badge primary-bg secondary">{{sent_friendship_requests|length}}</span>
    </a>
</li>
{% endblock %}

{% block dashboard_content %}
    {% for friendship_request in sent_friendship_requests %}
       {% include "friendship/sent_request.html" %}
    {% empty %}
        <p>You have not sent any friend request.</p>
    {% endfor %}
{% endblock %}

custom_account/templates/custom_account/login_form.html
{% extends "custom_account/dashboard_base.html" %}
{% block title %}tasks list{% endblock %}

{% block content %}
    <section class="form-container">
        <h3>Login</h3>
        <div class="form-heading-container">
            <h3 class="secondary">Login</h3> 
            <a href="{% url 'account_signup' %}">Sign Up</a>
        </div>
        <form action="{% url 'custom_account:login' %}" method="post">
            {% csrf_token %}
            <p>{{form.as_p}}</p>
            <input type="submit" value="Login"/>
        </form>
        <p>
            <a href="{% url 'google_login' %}">Log in with Google</a>
        </p>
        <br>
        <!-- <a href="{% url 'custom_account:signup' %}">signup</a> -->
    </section>
{% endblock %}

custom_account/templates/custom_account/profile.html
{% extends 'base.html' %}

{% block title %}tasks list{% endblock %}

{% block content %}
   <h2>Welcome to profile page, {{user.email}}</h2>
{% endblock %}

custom_account/templates/custom_account/signup_form.html
{% extends "custom_account/dashboard_base.html" %}

{% block title %}tasks list{% endblock %}

{% block content %}
    <section class="form-container">
        <h3>Sign up</h3>
        <div class="form-heading-container">
            <h3 class="secondary">Sign In</h3> 
            <a href="{% url 'account_login' %}">Login</a>
        </div>
        <form action="{% url 'custom_account:signup' %}" method="post">
            {% csrf_token %}
            <p>{{form.as_p}}</p>
            <input type="submit" value="Sign up"/>
        </form>
        <br>
        <a href="{% url 'custom_account:login' %}">Login</a>
    </section>
{% endblock %}

custom_account/templates/custom_account/user.html
<article class="review">
    <img src="{{user.profile.photo.url|default:'/static/images/avatar.jpg'}}" width="100" height="100"
        alt="{{user.username}}" 
        class="shadow rounded"
        />
    <a href="{% url 'custom_account:detail' user.id %}" class="btn-secondary">{{user.username}}</a>
</article>

custom_account/templates/custom_account/user_detail.html
{% extends "custom_account/dashboard_base.html" %}
{% block content %}
    <section class="details-container padding-main-x">
        <header class="detail-header" style="margin-bottom: 20px;">
            <img src="{{user.photo.url|default:'/static/images/avatar.jpg'}}"
                class="rounded shadow detail-image" width="100" height="100"
            />
            <div class="detail-text-container">
                <h2 class="detail-name">{{user.username}}</h2>
                <!-- <p>{{item.description}}</p> -->
                {% if user.fullname %}
                    <h3 class="primary">{{user.fullname}}</h3>
                {% endif %}
            </div>
        </header>
        <a href="{% url 'friendship:request' pk=request.user.id friend_id=user.id %}" 
            class="btn-bordered-primary">
            <i class="fa-solid fa-share fa-xl"></i>Send friend request
        </a>
    </section>
{% endblock %}