budget/urls.py
from django.urls import path
from . import views

app_name = 'budget'
urlpatterns = [
    path('', views.BudgetCreateView.as_view(), name='create'),
    path('list/', views.BudgetListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.BudgetDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.BudgetUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.BudgetDeleteView.as_view(), name='delete'),
]

custom_account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from django.conf.urls.static import static


app_name = 'custom_account'
urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard-friendships/', views.dashboard_friendship, name='friendship'),
    path(
        'dashboard-sent-requests/',
        views.dashboard_sent_friendship_requests, 
        name='sent-requests'
    ),
    path(
        'dashboard-received-requests/',
        views.dashboard_received_friendship_requests, 
        name='received-requests'
    ),
    path(
        'dashboard-budgets/',
        views.dashboard_budgets,
        name='budgets'
    ),
    path(
        'user/<int:pk>/', 
        views.UserDetailView.as_view(), 
        name='detail'
    ),
]

errand/urls.py
from django.contrib import admin
from django.urls import path, include
from custom_account.views import home as home_view
from django.conf.urls.static import static
from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('custom-accounts/', include('custom_account.urls')),
    path('item/', include('item.urls')),
    path('sharing/', include('sharing.urls')),
    path('friendship/', include('friendship.urls')),
    path('budget/', include('budget.urls')),
    path('', home_view)
]

if DEBUG:
     urlpatterns+=static(MEDIA_URL, document_root=MEDIA_ROOT)

item/urls.py
from django.urls import path
from . import views

app_name = 'item'
urlpatterns = [
    path('item/<int:budget_id>/', views.ItemCreateView.as_view(), name='create'),
    path('list/', views.ItemListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.ItemDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', views.ItemDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', views.ItemUpdateView.as_view(), name='update'),
]

sharing/urls.py
from django.urls import path
from . import views

app_name = 'sharing'

urlpatterns = [
    path('share-item/<int:pk>/', views.ShareItemView.as_view(), name='share-item'),
    path('share-budget/<int:pk>/', views.ShareBudgetView.as_view(), name='share-budget'),
    path('unshare/<int:pk>/<int:target_user_pk>/', views.ShareDeleteView.as_view(), name='delete'),
]

budget/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.db.models import Sum
from django.contrib.contenttypes.fields import GenericRelation
from sharing.models import Share


class Budget(models.Model):
    """
    Budget that groups related items. 
    Each budget has items which can be managed. 
    """
    CURRENCY = (
        ('N', 'Naira'),
        ('$', 'US Dollar'),
    )
    name = models.CharField(max_length=70, unique=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    currency = models.CharField(max_length=1, choices=CURRENCY, default='N')
    shares = GenericRelation(Share)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('budget:detail', kwargs={'pk': self.pk})

    def get_total_cost(self):
        total_cost = self.item_set.all().filter(
            budget__id=self.id
        ).aggregate(total_cost=Sum('price'))
        return total_cost.get('total_cost')

item/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse
from budget.models import Budget
from django.contrib.contenttypes.fields import GenericRelation
from sharing.models import Share


class Comment(models.Model):
    """
    What users discuss about item.
    """
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"comment by {self.user.username}"


class Item(models.Model):
    """
    Model to represent Item that a user want to acquire/buy
    directly or indirectly.
    """
    name = models.CharField(max_length=150)
    description = models.TextField()
    budget = models.ForeignKey(Budget, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    done = models.BooleanField(default=False)
    photo = models.ImageField(upload_to='items')
    accepted = models.BooleanField(default=False)
    comments = models.ManyToManyField(Comment, blank=True)
    shares = GenericRelation(Share)

    def __str__(self):
        return self.name

budget/forms.py
from django import forms
from .models import Budget


class BudgetForm(forms.ModelForm):

    class Meta:
        model = Budget
        fields = ('name', 'description', )

budget/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Budget
from django.urls import reverse
from .forms import BudgetForm
from django.db.models import Sum
from django.http import HttpResponseRedirect


class BudgetCreateView(LoginRequiredMixin, generic.CreateView):
    model = Budget
    form_class = BudgetForm

    def form_valid(self, form, *args, **kwargs):
        form.instance.owner = self.request.user
        form.save()
        return super().form_valid(form, *args, **kwargs)


class BudgetListView(LoginRequiredMixin, generic.ListView):
    model = Budget


class BudgetDetailView(LoginRequiredMixin, generic.DetailView):
    model = Budget

    # def get_context_data(self, *args, **kwargs):
    #     context = super().get_context_data(*args, **kwargs)
    #     context.update(self.get_total_cost())
    #     return context

    # def get_total_cost(self):
    #     """
    #     Returns the sum of cost of all items in a budget.
    #     """
    #     total_cost = self.get_object().item_set.all().aggregate(total_cost=Sum('price'))
    #     return total_cost


class BudgetUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Budget
    form_class = BudgetForm
    template_name = 'budget/budget_update_form.html'

    def get_success_url(self):
        return reverse('budget:detail', kwargs={'pk':self.kwargs.get('pk')})


class BudgetDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Budget

    def get_success_url(self):
        return HttpResponseRedirect(reverse('custom_account:budgets'))

budget/templates/budget/budget.html
<article class="budget">
    <h3>{{budget.name}}</h3>
    <div class="budget-body" style="color: grey;">
        <h4>{{budget.item_set.all|length}} item{{budget.item_set.all|pluralize}}</h4>
        <small class="date">{{budget.created_at.date}}</small>
        <h4 class="color warning">{{budget.currency}}{{budget.get_total_cost|default:0}}</h4>
    </div>
    <a href="{% url 'budget:detail' budget.id %}" class="btn">detail...</a>
</article>

budget/templates/budget/budget_confirm_delete.html
{% extends "custom_account/dashboard_base.html" %}
{% block title %}delete budget{% endblock %}

{% block content %}
    <section class="form-container">
        <div class="form-heading-container">
            <h3>Do you want to delete</h3>
        </div>
        <div style="padding: 50px;">
            {% include "budget/budget.html" %}
        </div>
        <form action="{% url 'budget:delete' budget.id %}" method="post">
            {% csrf_token %}
            <p>{{form.as_p}}</p>
            <input type="submit" value="Yes"/>
            <a href="{% url 'budget:detail' budget.id %}">No</a>
        </form>
    </section>
{% endblock %}

budget/templates/budget/budget_detail.html
{% extends "custom_account/dashboard_base.html" %}
{% block content %}
    <section class="details-container padding-main-x">
        <header class="detail-header" style="margin-bottom: 20px;">
            <div class="detail-text-container">
                <h2 class="detail-name">{{budget.name}}</h2>
                <p>{{budget.description}}</p>
            </div>
            <div
                style="display: flex; justify-content: space-around;">
                <div>
                    <h3 style="display: inline-block;">{{budget.item_set.all|length}} item{{budget.item_set.all|pluralize}}</h3>
                    <a href="{% url 'item:create' budget.id %}" class="btn btn-small primary">
                        <i class="fa-solid fa-plus fa-sm"></i> Add Item 
                    </a>
                </div>
                <h3>{{budget.currency}}{{budget.get_total_cost|default:0}}</h3>
                <small>{{budget.created_at.date}}</small>
            </div>
        </header>    
        <article class="shared-users padding-main reviews-container">

            {% for item in budget.item_set.all %}
                {% include "item/item.html" %}
            {% empty %}
                <p>Item not shared yet.</p>
            {% endfor %}
        </article>

        <hr>
        <a href="{% url 'sharing:share-budget' budget.id %}" class="btn-bordered-primary"><i class="fa-solid fa-share fa-xl"></i>Share</a>
        <a href="{% url 'budget:update' budget.id %}" class="btn-bordered-primary"><i class="fa-solid fa-pencil fa-xl"></i>Edit</a>
        <a href="{% url 'budget:delete' budget.id %}" class="btn primary"><i class="fa-solid fa-trash fa-xl"></i>Delete</a>
    </section>
{% endblock %}

budget/templates/budget/budget_form.html
{% extends "custom_account/dashboard_base.html" %}
{% block title %}create budget{% endblock %}
{% block content %}
    <section class="form-container">
        <div class="form-heading-container">
            <h3>New Budget</h3>
        </div>
        <form action="{% url 'budget:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{form.as_p}}</p>
            <input type="submit" value="Submit"/>
            <a href="{% url 'custom_account:budgets' %}">See budgets</a>
        </form>
    </section>
{% endblock %}

budget/templates/budget/budget_update_form.html
{% extends "custom_account/dashboard_base.html" %}
{% block title %}budget update{% endblock %}

{% block content %}
    <section class="form-container">
        <div class="form-heading-container">
            <h3>Budget Update</h3>
        </div>
        <form action="{% url 'budget:update' budget.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{form.as_p}}</p>
            <input type="submit" value="Submit"/>
            <a href="{% url 'custom_account:dashboard' %}">Cancel</a>
        </form>
    </section>
{% endblock %}