budget/urls.py
from django.urls import path
from . import views

app_name = 'budget'
urlpatterns = [
    path('', views.BudgetCreateView.as_view(), name='create'),
    path('list/', views.BudgetListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.BudgetDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.BudgetUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.BudgetDeleteView.as_view(), name='delete'),
]

custom_account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from django.conf.urls.static import static


app_name = 'custom_account'
urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard-friendships/', views.dashboard_friendship, name='friendship'),
    path(
        'dashboard-sent-requests/',
        views.dashboard_sent_friendship_requests, 
        name='sent-requests'
    ),
    path(
        'dashboard-received-requests/',
        views.dashboard_received_friendship_requests, 
        name='received-requests'
    ),
    path(
        'dashboard-budgets/',
        views.dashboard_budgets,
        name='budgets'
    ),
    path(
        'user/<int:pk>/', 
        views.UserDetailView.as_view(), 
        name='detail'
    ),
]

errand/urls.py
from django.contrib import admin
from django.urls import path, include
from custom_account.views import home as home_view
from django.conf.urls.static import static
from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('custom-accounts/', include('custom_account.urls')),
    path('item/', include('item.urls')),
    path('sharing/', include('sharing.urls')),
    path('friendship/', include('friendship.urls')),
    path('budget/', include('budget.urls')),
    path('', home_view)
]

if DEBUG:
     urlpatterns+=static(MEDIA_URL, document_root=MEDIA_ROOT)

friendship/urls.py
from django.urls import path
from . import views

app_name = 'friendship'

urlpatterns = [
    path(
        'unfriend/<int:pk>/', 
        views.UnfriendView.as_view(), 
        name='unfriend'
    ),
    path(
        'block/<int:pk>/',
        views.BlockUnblockUserView.as_view(),
        name='block'
    ),
    path(
        'search/',
        views.friend_search,
        name='search'
    ),
    path(
        'request/<int:pk>/<int:friend_id>/',
        views.CreateFriendshipRequest.as_view(),
        name='request'
    ),
    path(
        'accept/<int:friend_id>/',
        views.AcceptFriendshipRequest.as_view(),
        name='accept'
    )
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'
urlpatterns = [
    path('item/<int:budget_id>/', views.ItemCreateView.as_view(), name='create'),
    path('list/', views.ItemListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.ItemDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', views.ItemDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', views.ItemUpdateView.as_view(), name='update'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/2a58cf95b4.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block header %}
        <header class="header">
            {% include "brand.html" %}
            {% include "search_form.html" %}
            {% include "nav.html" %}
            <i class="fas fa-bars"></i>
        </header>
    {% endblock %}

    <main>{% block content %} {% endblock %}</main>
    {% block script %}<script src="{% static 'script.js' %}"></script>{% endblock %}
    <footer>
        {% include 'brand.html' %}
        <p>&copy;2022 Xpendio. All rights reserved</p>
    </footer>
</body>
</html>

templates/brand.html
{% load static %}

<div class="brand">
    <a href="/" class="nav-link"><img src="{% static 'images/logo.png' %}" alt="logo" class="brand-logo"/></a>
    <a href="/" class="nav-link"><h2 class="brand-name">Xpendio</h2></a>
</div>

templates/email_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body style="margin: 0% 10%;">
        <div
            style="
                background-color: rgb(0, 100, 100);
                color: white;
                padding: 2% 5%;
                border-radius: 10px;
                font-family: broadway, forte;
            ">
            <h1 style="color: white; text-align: center;">Errand</h1>
        </div>
        <div
            style="
                padding: 2%; 
                color: black;
                background-color: white; 
                font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
                "
            >
            {% block content %}{% endblock %}
            {% block footer %}
                <div style="margin-top: 20px;">
                    <a href="{{request.scheme}}://{{request.get_host}}{% url 'custom_account:received-requests' %}"
                        style="
                            text-decoration: none; 
                            display: block; 
                            background-color: rgb(0, 100, 100); 
                            color: white;
                            border-radius: 10px;
                            padding: 10px 30px;
                            width: fit-content;
                            "      
                    >Manage request
                    </a>
                </div>
            {% endblock %}
        </div>
    </body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %} home {% endblock %}
{% block content %}
    <section class="landing">
        <article class="landing-text">
            <h1 class="landing-title">Manage budget without using Paper</h1>
            <p class="landing-body">
               Xpendio is a place where you easily manage your expenditure.
            </p>
            <p class="landing-body">
                Xpendio enables you to create budget without having to carry pen and papper.
                You don't have to worry about losing budget. 
             </p>
            <br>
            <a href="{% url 'budget:create' %}" class="btn landing-btn" style="margin-top: 2%;">Create Budget</a>
        </article>
        <article>
            <img src="{% static 'images/logo.png' %}" alt="inner-image" class="inner-image rounded">
            <img src="{% static 'images/expendio-outer.png' %}" alt="landing-image" class="landing-image rounded">
        </article>
    </section>

    <section class="errand-description">
        
        <article class="errand-text">
            <h3 class="title color-primary">Things you can do with Xpendio</h3>
            <p>
                Xpendio helps to eliminate the use of paper to manage your budget.
                Managing budget on paper can be boring and dangerous because it can be misplaced. 
                Xpendio helps you to: 
            </p>
            <ul class="errand-items">
                <li class="errand-item">Create budget which you can access anytime, anywhere</li>
                <li class="errand-item">Share budget without people that matter</li>
                <li class="errand-item">Share item of a budget with people</li>
            </ul>
            <div>
                <h2 style="margin: 20px 0px;">Start Using Xpendio now</h2>
                <a href="{% url 'budget:create' %}" class="btn landing-btn" style="margin-top: 2%;">Create Budget</a>
            </div>
        </article>
    </section>
    <section class="reviews" style="background-color:white;">
        <h3 style="" class="title primary-color">What people say about "Errand"</h3>
        <div class="reviews-container">
            {% for review in reviews %}
                {% include "reviews/review.html" %}
            {% endfor %}
        </div>
    </section>
{% endblock %}

templates/nav.html
{% load static %}
{% block nav %}
    <nav>
        {% include 'brand.html' %}
        <ul class="nav-items">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'custom_account:friendship' %}">Friends</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'custom_account:received-requests' %}">Received requests</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'custom_account:sent-requests' %}">Sent requests</a>
            </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'custom_account:budgets' %}">Budgets</a></li>
        </ul>
        <ul class="account-links">
            {% if user.is_authenticated %}
                <div class="image-logout-wrapper">
                    <img src="{% static '/images/logo.png' %}" alt="" width="50" height="50">
                    <li class="btn-bordered-primary"><a class="nav-link" href="{% url 'account_logout' %}">logout</a></li>
                </div>
            {% else %}
                <li class="btn-bordered-primary"><a class="nav-link" href="{% url 'account_login' %}">login</a></li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

templates/search_form.html
<form class="search-form" 
    action="{% url 'friendship:search' %}" 
    onsubmit=false>
    <div class="search-form-group">
        <input type="search" 
            placeholder="Enter friend's username"
            name="username"
            autofocus
            id="search-username"
        />
        <i class="fas fa-search"></i>
    </div>
</form>

templates/search_result.html
{% extends "base.html" %}
{% load static %}
{% block title %} search results{% endblock %}
{%  block content %}
    <section class="reviews-container padding-main">
        {% for user in users %}
            {% include 'custom_account/user.html' %}
        {% empty %}
            <h3>No user with username <q>{{username}}</q></h3>
        {% endfor %}
    </section>
{% endblock %}