budget/urls.py
from django.urls import path
from . import views

app_name = 'budget'
urlpatterns = [
    path('', views.BudgetCreateView.as_view(), name='create'),
    path('list/', views.BudgetListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.BudgetDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.BudgetUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.BudgetDeleteView.as_view(), name='delete'),
]

custom_account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from django.conf.urls.static import static


app_name = 'custom_account'
urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard-friendships/', views.dashboard_friendship, name='friendship'),
    path(
        'dashboard-sent-requests/',
        views.dashboard_sent_friendship_requests, 
        name='sent-requests'
    ),
    path(
        'dashboard-received-requests/',
        views.dashboard_received_friendship_requests, 
        name='received-requests'
    ),
    path(
        'dashboard-budgets/',
        views.dashboard_budgets,
        name='budgets'
    ),
    path(
        'user/<int:pk>/', 
        views.UserDetailView.as_view(), 
        name='detail'
    ),
]

errand/urls.py
from django.contrib import admin
from django.urls import path, include
from custom_account.views import home as home_view
from django.conf.urls.static import static
from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('custom-accounts/', include('custom_account.urls')),
    path('item/', include('item.urls')),
    path('sharing/', include('sharing.urls')),
    path('friendship/', include('friendship.urls')),
    path('budget/', include('budget.urls')),
    path('', home_view)
]

if DEBUG:
     urlpatterns+=static(MEDIA_URL, document_root=MEDIA_ROOT)

item/urls.py
from django.urls import path
from . import views

app_name = 'item'
urlpatterns = [
    path('item/<int:budget_id>/', views.ItemCreateView.as_view(), name='create'),
    path('list/', views.ItemListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.ItemDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', views.ItemDeleteView.as_view(), name='delete'),
    path('update/<int:pk>/', views.ItemUpdateView.as_view(), name='update'),
]

sharing/urls.py
from django.urls import path
from . import views

app_name = 'sharing'

urlpatterns = [
    path('share-item/<int:pk>/', views.ShareItemView.as_view(), name='share-item'),
    path('share-budget/<int:pk>/', views.ShareBudgetView.as_view(), name='share-budget'),
    path('unshare/<int:pk>/<int:target_user_pk>/', views.ShareDeleteView.as_view(), name='delete'),
]

sharing/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey


class Share(models.Model):
    """
    Model to represent instance of sharing item
    with a user.

    This could be ab item that a user wants someone to buy for him. 
    The target user is the person helping the owner. 
    """
    # item = models.ForeignKey(Item, on_delete=models.CASCADE)
    target_users = models.ManyToManyField(settings.AUTH_USER_MODEL)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return f"{self.pk}"

sharing/forms.py
from . models import Share
from django import forms


class ShareForm(forms.ModelForm):

    class Meta:
        model = Share
        fields = ('target_users',)

sharing/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from .models import Share
from item.models import Item
from .forms import ShareForm
from django.contrib.auth.models import User
from friendship.models import Friendship
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.mail import EmailMessage
from .utils  import send_email, get_target_users_email
from budget.models import Budget


class ShareItemView(LoginRequiredMixin, generic.CreateView):
    """
    View to allow user to share item with another user.
    """
    model = Share
    fields = ('target_users',)
    shared_model = Item # model of the item/budget to be shared
    email_subject = "Sharing Item"
    template_name = 'sharing/share_item_form.html'
    item_key = "item"

    def get_success_url(self, *args, **kwargs):
        return reverse('item:detail', kwargs={'pk': self.kwargs.get('pk')})

    def get(self, request, *args, **kwargs):
        item = get_object_or_404(Item, pk=kwargs.get('pk'))
        form = self.get_form_class()

        # get user queryset for active friends
        active_friends_queryset = get_user_model().objects.filter(
            id__in=self.get_active_friends_ids()
        ).exclude(id__exact=request.user.id)

        # set the select options by overiding the queryset
        # property of the form 
        form.base_fields['target_users'].queryset = active_friends_queryset
        return render(
            request,
            self.template_name, 
            {
                self.item_key:self.get_shared_object(), 
                'form': form,
                'active_friendships': self.get_active_friendships(),
                'target_users': active_friends_queryset
            }
        )
    
    def get_active_friendships(self):
        """
        Returns user's friends whom are not blocked.
        """
        active_friendships = Friendship.objects.filter(status__iexact='AC', blocked=False)
        return active_friendships

    def get_active_friends_ids(self):
        """
        Returns the list of active friends ids
        """
        friends_ids = [ friendship.friend.id for friendship in self.get_active_friendships()]
        return friends_ids
    
    def add_instance_properties(self, form):
        """
        Defines user, target_users and content_object
        properties of the Share Model instance.
        """
        # form.instance.user = self.request.user
        # form.instance.item = Item.objects.get(id=self.kwargs.get('pk'))
        form.instance.content_object = self.get_shared_object()
        # super().form_valid(form)
        target_users = get_user_model().objects.filter(id__in=form.cleaned_data.get('target_users'))
        print('users', target_users)
        form.instance.target_users.set(target_users)
        form.save()

    def form_valid(self, form): 
        self.add_instance_properties(form)

        context = {
            "item": self.get_shared_object(),
            "request": self.request
        }
        # send email notification
        send_email(
            self.email_subject,
            get_target_users_email(target_users),
            self.get_shared_object(),
            context,
            "sharing/email/share_notification.html"
        )
        return super().form_valid(form)

    def get_shared_object(self):
        """
        Returns item to be shared
        """
        return get_object_or_404(self.shared_model, id=self.kwargs.get('pk'))
        

class ShareBudgetView(ShareItemView):
    """
    View for sharing Budget with friends.
    """
    model = Share
    shared_model = Budget
    email_subject = "Sharing Budget"
    template_name = 'sharing/share_budget_form.html'
    item_key = "budget"


class ShareDeleteView(LoginRequiredMixin, generic.DeleteView):
    """
    View to unshare item with users.
    """
    model = Share
    context_object_name = 'share'

    def get_context_data(self, *args, **kwargs):
        """
        Add target user to the context.
        """
        context = super().get_context_data(*args, **kwargs)
        context['target_user'] = self.get_target_user_object()
        return context

    def get_target_user_object(self):
        """
        Query target user that an item will be unshared with.
        """
        target_user_object = get_object_or_404(
                get_user_model(), pk=self.kwargs.get('target_user_pk')
        )
        return target_user_object

    def post(self, *args, **kwargs):
        """
        Delete target user from a share. Delete share also there
        is no target user associated with it.
        """
        share = self.get_object()
        item_id = share.item.id
        try:
            target_user = self.get_target_user_object()
            share.target_users.remove(self.get_target_user_object())
            context = {
                "item": share.item,
                "request": self.request
            }
            # send email notification
            send_email(
                "Unsharing Item",
                [target_user.email],
                share.item,
                context,
                "sharing/email/unshare_notification.html"
            )
        except Exception as e:
            print(f'Error: { e}')

        if len(share.target_users.all()) == 0:
            # remove share instance when no target user is 
            # associated with it.
            share.delete()
        return HttpResponseRedirect(reverse('item:detail', kwargs={'pk': item_id}))
        

sharing/templates/sharing/share_budget_form.html
{% extends "custom_account/dashboard_base.html" %}
{% block content %}
    <div class="form-container">
        <!-- <h3>Share item </h3> -->
        <small>
            {% for error in forms.errors %}
                {{error}}
            {% endfor %}
        </small>
        <div class="form-heading-container">
            <h3>You are sharing:</h3>
        </div>
        <div style="padding: 50px;">
            {% include "sharing/shared_budget.html" %}
        </div>

        <form method="post" action="{% url 'sharing:share-budget' budget.id %}">
            {% csrf_token %}
            <h4 id=>with:</h4>
            <ul id="selected-target-users">

            </ul>
            <section class="target-users-container" style="text-align: center;">
                {% for target_user in target_users %}
                    <article class="target-user" onclick="()=>{console.log('hello')}">
                        <input id="checkbox-{{forloop.counter0}}" type="checkbox" name="target_users" value="{{target_user.id}}"/>
                        <label id="label-{{forloop.counter0}}">{{target_user.username}}</label>
                        <img src="{{target_user.profile.photo.url|default:'/static/images/avatar.jpg'}}" width="50" height="50"
                        alt="{{review.name}}" 
                        class="shadow rounded"
                        />
                    </article>
                {% empty %}
                    <small> You don't have any active friend</small>
                    <a href="{% url 'custom_account:friendship' %}" class="btn-secondary">Manage friends</a>
                {% endfor %}
            </section>
            <input type="submit" value="Ok">
            <a href="{% url 'budget:detail' budget.id %}" class="">Cancel</a>
        </form>
    </div>
{% endblock %}

sharing/templates/sharing/share_confirm_delete.html
{% extends "custom_account/dashboard_base.html" %}
{% block content %}
    <div class="form-container">
        <!-- <h3>Share item </h3> -->
        <small>
            {% for error in forms.errors %}
                {{error}}
            {% endfor %}
        </small>
        <div class="form-heading-container">
            <h3>You are unsharing:</h3>
        </div>
        <div style="padding: 50px;">
            {% include "sharing/share_item.html" with item=share.item %}
        </div>

        <form method="post" action="{% url 'sharing:delete' pk=share.id target_user_pk=target_user.id %}" >
            {% csrf_token %}
            <h4 id=>with:</h4>
            <section class="target-users-container">
                {% include 'friendship/user.html' with friend=target_user %}
            </section>
            <input type="submit" value="Ok">
            <a href="{% url 'item:detail' share.item.id %}" class="">Cancel</a>
        </form>
    </div>
{% endblock %}

sharing/templates/sharing/share_form.html
{% extends "custom_account/dashboard_base.html" %}
{% block content %}
    <div class="form-container">
        <!-- <h3>Share item </h3> -->
        <small>
            {% for error in forms.errors %}
                {{error}}
            {% endfor %}
        </small>
        <div class="form-heading-container">
            <h3>You are sharing:</h3>
        </div>
        <div style="padding: 50px;">
            {% include "sharing/share_item.html" %}
        </div>

        <form method="post" action="{% url 'sharing:share' item.id %}">
            {% csrf_token %}
            <h4 id=>with:</h4>
            <ul id="selected-target-users">

            </ul>
            <section class="target-users-container" style="text-align: center;">
                {% for target_user in target_users %}
                    <article class="target-user" onclick="()=>{console.log('hello')}">
                        <input id="checkbox-{{forloop.counter0}}" type="checkbox" name="target_users" value="{{target_user.id}}"/>
                        <label id="label-{{forloop.counter0}}">{{target_user.username}}</label>
                        <img src="{{target_user.profile.photo.url|default:'/static/images/avatar.jpg'}}" width="50" height="50"
                        alt="{{review.name}}" 
                        class="shadow rounded"
                        />
                    </article>
                {% empty %}
                    <small> You don't have any active friend</small>
                    <a href="{% url 'custom_account:friendship' %}" class="btn-secondary">Manage friends</a>
                {% endfor %}
            </section>
            <input type="submit" value="Ok">
            <a href="{% url 'item:detail' item.id %}" class="">Cancel</a>
        </form>
    </div>
{% endblock %}

sharing/templates/sharing/share_item.html
<article class="review">
    <img src="{{item.photo.url}}" width="100" height="100"
        alt="{{item.name}}" 
        class="shadow rounded"
        />
    <h4 class="primary review-author">
        <a href="{% url 'item:detail' item.id %}" class="btn-secondary">{{item.name}}</a>|
        <span class="time warning">{{item.created_at|date:"M, d Y"}}</span>
    </h4>
    {% include "item/shared_with.html" with shared_with_users=item.share_set.all %}
</article>

sharing/templates/sharing/share_item_form.html
{% extends "custom_account/dashboard_base.html" %}
{% block content %}
    <div class="form-container">
        <!-- <h3>Share item </h3> -->
        <small>
            {% for error in forms.errors %}
                {{error}}
            {% endfor %}
        </small>
        <div class="form-heading-container">
            <h3>You are sharing:</h3>
        </div>
        <div style="padding: 50px;">
            {% include "sharing/share_item.html" %}
        </div>

        <form method="post" action="{% url 'sharing:share-item' item.id %}">
            {% csrf_token %}
            <h4 id=>with:</h4>
            <ul id="selected-target-users">

            </ul>
            <section class="target-users-container" style="text-align: center;">
                {% for target_user in target_users %}
                    <article class="target-user" onclick="()=>{console.log('hello')}">
                        <input id="checkbox-{{forloop.counter0}}" type="checkbox" name="target_users" value="{{target_user.id}}"/>
                        <label id="label-{{forloop.counter0}}">{{target_user.username}}</label>
                        <img src="{{target_user.profile.photo.url|default:'/static/images/avatar.jpg'}}" width="50" height="50"
                        alt="{{review.name}}" 
                        class="shadow rounded"
                        />
                    </article>
                {% empty %}
                    <small> You don't have any active friend</small>
                    <a href="{% url 'custom_account:friendship' %}" class="btn-secondary">Manage friends</a>
                {% endfor %}
            </section>
            <input type="submit" value="Ok">
            <a href="{% url 'item:detail' item.id %}" class="">Cancel</a>
        </form>
    </div>
{% endblock %}

sharing/templates/sharing/shared_budget.html
<article class="review">
    <h4 class="primary review-author">
        <a href="{% url 'budget:detail' budget.id %}" class="btn-secondary">{{budget.name}}</a>|
        <span class="time warning">{{item.created_at|date:"M, d Y"}}</span>
    </h4>
    {% include "budget/budget.html" with shared_with_users=budget.shares.all %}
</article>